import type { Metadata } from "next";
import Link from "next/link";
import { siteConfig } from "@/data/site";
import { featureRecords } from "@/data/features";
import { AdsterraArticleBottom, AdsterraArticleMid, AdsterraArticleTop } from "@/components/ads";
import { BreadcrumbJsonLd } from "@/components/seo/JsonLd";
import { Breadcrumbs, PageIntro, SectionHeader } from "@/components/ui/content";

const groups = [
  {title:"Release and access",body:"Official preview date, client links, access questions and progress-persistence status.",href:"/preview",items:["announcement","preview-date","official-client","preview-access","progress"]},
  {title:"Features and side activities",body:"Implementation states for original-game features without assuming PokeMMO parity.",href:"/features",items:["pwt","pokestar","join-avenue","tower-treehollow","roaming"]},
  {title:"Teams and progression",body:"Role criteria, ranking limits and the data needed before exact locations, caps or teams can publish.",href:"/tier-list",items:[]}
];
export const metadata: Metadata={title:"PokeMMO B2/W2 Wiki & Evidence Index",description:"Browse a source-labelled PokeMMO B2/W2 feature and entity index that distinguishes official MMO evidence from original-game references.",alternates:{canonical:`${siteConfig.domain}/wiki`}};
export default function WikiPage(){return <main className="mx-auto max-w-7xl px-4 py-10"><BreadcrumbJsonLd items={[{name:"Home",href:"/"},{name:"Evidence Index",href:"/wiki"}]}/><Breadcrumbs items={[{label:"Evidence Index",href:"/wiki"}]}/><PageIntro eyebrow="Unofficial evidence index" title="PokeMMO B2/W2 wiki and status index" description="Find the best current page for each B2/W2 question. Cards tell you what has evidence now and which exact-data pages are still waiting for the preview."/><AdsterraArticleTop/>
    <section className="mt-10 grid gap-4 lg:grid-cols-3">{groups.map((group)=><article key={group.title} className="content-card"><h2 className="text-xl font-bold text-white">{group.title}</h2><p className="mt-3 text-sm leading-6 text-white/65">{group.body}</p>{group.items.length?<p className="mt-4 text-xs text-white/45">{group.items.length} tracked records</p>:<p className="mt-4 text-xs text-amber-200">Exact gameplay data pending</p>}<Link href={group.href} className="mt-5 inline-flex text-sm font-bold text-cyan-300 hover:underline">Open this topic →</Link></article>)}</section>
    <AdsterraArticleMid/><section className="mt-10"><SectionHeader eyebrow="Tracked now" title="Evidence-aware topic cards" copy="These cards point to the page that owns the full answer and source trail."/><div className="mt-6 grid gap-4 md:grid-cols-2">{featureRecords.slice(0,6).map((item)=><article key={item.id} className="content-card"><div className="flex items-center justify-between gap-3"><h2 className="font-bold text-white">{item.title}</h2><span className="status-pill">{item.state.replace("-"," ")}</span></div><p className="mt-3 text-sm leading-6 text-white/65">{item.summary}</p><Link className="mt-4 inline-flex text-sm text-cyan-300 hover:underline" href={item.id === "pwt" || item.id === "pokestar" || item.id === "join-avenue" || item.id === "tower-treehollow" ? "/features/side-content" : "/features"}>See full status →</Link></article>)}</div></section>
    <section className="mt-10 content-card"><SectionHeader eyebrow="Waiting for preview evidence" title="Pages we will not fake"/><div className="mt-5 grid gap-4 md:grid-cols-3"><div><h3 className="font-bold text-white">Pokémon locations</h3><p className="mt-2 text-sm text-white/60">Needs direct encounter capture and a second source.</p></div><div><h3 className="font-bold text-white">Level caps</h3><p className="mt-2 text-sm text-white/60">Needs observed PokeMMO progression gates.</p></div><div><h3 className="font-bold text-white">Story route</h3><p className="mt-2 text-sm text-white/60">Needs preview checkpoints; cartridge walkthroughs are not enough.</p></div></div></section>
    <nav className="mt-8 flex flex-wrap gap-3"><Link className="button-secondary" href="/features">Feature tracker</Link><Link className="button-secondary" href="/tier-list">Team-role evidence</Link><Link className="button-secondary" href="/guides">Guides</Link><Link className="button-secondary" href="/sources">Sources</Link></nav><AdsterraArticleBottom/></main>}
