import type { Metadata } from "next";
import Link from "next/link";
import { siteConfig } from "@/data/site";
import { AdsterraArticleBottom, AdsterraArticleMid, AdsterraArticleTop } from "@/components/ads";
import { BreadcrumbJsonLd, FaqJsonLd } from "@/components/seo/JsonLd";
import { Breadcrumbs, PageIntro, SectionHeader } from "@/components/ui/content";

const faq=[{q:"What should I do before the PokeMMO B2/W2 preview?",a:"Confirm normal account access, bookmark official pages, review safe client guidance and choose a few questions you want to test."},{q:"Does this checklist guarantee preview access?",a:"No. It is personal preparation only; official PokeMMO instructions decide access."},{q:"Should I change ROM or client files now?",a:"Not without official instructions. Keep your current setup safe and use only official PokeMMO guidance."},{q:"What should I record during the preview?",a:"Record the time, route, observed behavior and screenshots where permitted. Separate direct observations from guesses and cartridge memories."}];
const steps=[
 {title:"Confirm ordinary account access",body:"Open the normal official client and make sure you can reach your account before event day. Resolve account or installation trouble through PokeMMO support, not through this independent site. Do not store a username or password in any checklist."},
 {title:"Bookmark the four official paths",body:"Save the PokeMMO homepage, forum, downloads page and support center. Last-minute access instructions should come from these surfaces or channels linked by them. A search result alone is not enough to justify installing a special client."},
 {title:"Keep your setup recoverable",body:"Avoid replacing files or downloading third-party bundles in anticipation of the event. If official instructions later require a change, read them completely and keep any personal backup that is appropriate for your existing installation."},
 {title:"Write three test questions",body:"Choose narrow questions such as whether one named side activity appears, where one progression gate occurs or whether a particular route differs. Narrow questions produce more reliable observations than trying to remember an entire cartridge walkthrough."},
 {title:"Label what you observe",body:"Write the date and approximate time, what you did, what appeared and whether you could reproduce it. Mark community claims as reports until another source or direct repeat supports them. Never present a cartridge-only fact as PokeMMO behavior."},
 {title:"Treat progress as temporary",body:"No official carry-over answer was found in the PokeMMO information checked on September 5. Enjoy the preview, test what matters to you and avoid making plans that depend on characters, items, currency or story progress persisting afterward."}
];
export const metadata:Metadata={title:"PokeMMO B2/W2 Preview Preparation Checklist",description:"Use a concise PokeMMO B2/W2 preview checklist for official client safety, account readiness, test questions and evidence-aware expectations.",alternates:{canonical:`${siteConfig.domain}/guides/preview-preparation`}};
export default function PreparationPage(){return <main className="mx-auto max-w-7xl px-4 py-10"><BreadcrumbJsonLd items={[{name:"Home",href:"/"},{name:"Guides",href:"/guides"},{name:"Preview Preparation",href:"/guides/preview-preparation"}]}/><FaqJsonLd items={faq}/><Breadcrumbs items={[{label:"Guides",href:"/guides"},{label:"Preview Preparation",href:"/guides/preview-preparation"}]}/><PageIntro eyebrow="Safe preparation · September 2026" title="How to prepare for the PokeMMO B2/W2 preview" description="A practical checklist for September 19 that protects your account, keeps unknowns visible and helps you collect useful observations without assuming cartridge parity."/><AdsterraArticleTop/>
 <section className="mt-10 grid gap-4 lg:grid-cols-[0.75fr_1.25fr]"><aside className="content-card"><SectionHeader eyebrow="Quick answer" title="Prepare the account, not an imaginary build" copy="Before the preview, the useful work is account access, official links, client safety and a short testing plan. Roster, cap and route advice must wait for evidence."/><div className="mt-5 rounded-xl border border-amber-300/20 bg-amber-300/5 p-4 text-sm leading-6 text-amber-100">Completing this list does not confirm access, an exact start time, file requirements or progress carry-over.</div></aside><article className="content-card"><SectionHeader eyebrow="Requirements" title="What you need"/><dl className="mt-5 grid gap-4 sm:grid-cols-2"><div><dt className="text-xs uppercase tracking-wide text-white/45">Account</dt><dd className="mt-1 text-white">Normal PokeMMO access</dd></div><div><dt className="text-xs uppercase tracking-wide text-white/45">Client</dt><dd className="mt-1 text-white">Official current download only</dd></div><div><dt className="text-xs uppercase tracking-wide text-white/45">Event date</dt><dd className="mt-1 text-white">September 19, 2026</dd></div><div><dt className="text-xs uppercase tracking-wide text-white/45">Exact time</dt><dd className="mt-1 text-amber-200">Not confirmed</dd></div></dl></article></section>
 <section className="mt-10"><SectionHeader eyebrow="Step by step" title="Six safe preparation steps"/><ol className="mt-6 grid gap-4">{steps.map((step,index)=><li key={step.title} className="content-card"><div className="flex gap-4"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-cyan-300 text-lg font-black text-slate-950">{index+1}</span><div><h2 className="text-xl font-bold text-white">{step.title}</h2><p className="mt-3 leading-7 text-white/65">{step.body}</p></div></div></li>)}</ol></section>
 <AdsterraArticleMid/><section className="mt-10 grid gap-4 md:grid-cols-3"><article className="content-card"><h3 className="font-bold text-white">Mistake: trusting a special download</h3><p className="mt-2 text-sm text-white/60">Wait for a matching official instruction. A promised preview client is not proof.</p></article><article className="content-card"><h3 className="font-bold text-white">Mistake: copying cartridge routes</h3><p className="mt-2 text-sm text-white/60">PokeMMO implementation can differ in availability, balance and progression.</p></article><article className="content-card"><h3 className="font-bold text-white">Mistake: reporting from memory</h3><p className="mt-2 text-sm text-white/60">Record reproducible observations with a date and precise context.</p></article></section>
 <section className="mt-10 content-card"><SectionHeader eyebrow="Questions" title="Preparation FAQ"/><div className="mt-5 grid gap-3">{faq.map((item)=><details key={item.q} className="rounded-xl border border-white/10 p-4"><summary className="cursor-pointer font-bold text-white">{item.q}</summary><p className="mt-3 text-sm leading-6 text-white/65">{item.a}</p></details>)}</div></section><nav className="mt-8 flex flex-wrap gap-3"><Link className="button-secondary" href="/guides">All guides</Link><Link className="button-secondary" href="/preview">Preview FAQ</Link><Link className="button-secondary" href="/download">Safe setup</Link><Link className="button-secondary" href="/features">Feature questions</Link></nav><AdsterraArticleBottom/></main>}
