import type { Metadata } from "next";
import Link from "next/link";
import { siteConfig } from "@/data/site";
import { AdsterraArticleBottom, AdsterraArticleMid, AdsterraArticleTop } from "@/components/ads";
import { BreadcrumbJsonLd, FaqJsonLd } from "@/components/seo/JsonLd";
import { Breadcrumbs, PageIntro, SectionHeader } from "@/components/ui/content";
const faq=[{q:"Where should I download PokeMMO?",a:"Use pokemmo.com/downloads, the official download page. This site does not distribute the client."},{q:"Does this site provide Pokémon ROM files?",a:"No. It never hosts or links ROM files. Players must legally own compatible game files and follow official PokeMMO instructions."},{q:"Is a Black 2 or White 2 ROM required for the preview?",a:"A preview-specific requirement was not confirmed in the official pages checked September 5, 2026."},{q:"Should I install a separate preview client?",a:"Only if an official PokeMMO announcement instructs you to. No separate client is recommended here."},{q:"What if setup fails?",a:"Use official PokeMMO support. Do not send account credentials or copyrighted files to this site."}];
export const metadata:Metadata={title:"PokeMMO B2/W2 Download & ROM Requirements Status",description:"Use official PokeMMO client and support links, check the current B2/W2 requirement status and avoid unsafe or unauthorized ROM downloads.",alternates:{canonical:`${siteConfig.domain}/download`}};
export default function DownloadPage(){return <main className="mx-auto max-w-7xl px-4 py-10"><BreadcrumbJsonLd items={[{name:"Home",href:"/"},{name:"Download Help",href:"/download"}]}/><FaqJsonLd items={faq}/><Breadcrumbs items={[{label:"Download Help",href:"/download"}]}/><PageIntro eyebrow="Official links only" title="Safe PokeMMO B2/W2 setup status" description="Use the official client and support pages. Preview-specific client and ROM requirements were not confirmed when we checked on September 5, 2026."/><AdsterraArticleTop/>
 <section className="mt-10 grid gap-4 md:grid-cols-2"><a className="content-card" href="https://pokemmo.com/en/downloads/" target="_blank" rel="noreferrer"><span className="mini-label">Official</span><h2 className="mt-3 text-xl font-bold text-white">PokeMMO downloads</h2><p className="mt-2 text-sm text-white/65">Get the current client directly from pokemmo.com.</p></a><a className="content-card" href="https://support.pokemmo.com/" target="_blank" rel="noreferrer"><span className="mini-label">Official</span><h2 className="mt-3 text-xl font-bold text-white">PokeMMO support</h2><p className="mt-2 text-sm text-white/65">Use official articles and tickets for installation or account help.</p></a></section>
 <section className="mt-10 grid gap-5 lg:grid-cols-[1.1fr_0.9fr]"><article className="content-card"><SectionHeader eyebrow="Current answer" title="B2/W2-specific requirements are not confirmed" copy="General support content still describes the current PokeMMO setup. We will update this answer only when preview instructions clearly name new requirements."/><p className="mt-5 text-sm leading-7 text-white/65">Do not interpret search results about the original Nintendo DS games as PokeMMO preview instructions. Avoid third-party pages that bundle clients, ask for passwords, claim guaranteed preview access or provide copyrighted game files.</p></article><aside className="content-card border-amber-300/20"><SectionHeader eyebrow="ROM safety" title="Own your compatible game files" copy="PokeMMO does not provide commercial game ROMs. This site neither supplies nor links them."/></aside></section>
 <AdsterraArticleMid/><section className="mt-10 content-card"><SectionHeader eyebrow="Questions" title="Download and requirements FAQ"/><div className="mt-5 grid gap-3">{faq.map((item)=><details key={item.q} className="rounded-xl border border-white/10 p-4"><summary className="cursor-pointer font-bold text-white">{item.q}</summary><p className="mt-3 text-sm text-white/65">{item.a}</p></details>)}</div></section><nav className="mt-8 flex flex-wrap gap-3"><Link className="button-secondary" href="/preview">Preview guide</Link><Link className="button-secondary" href="/trello">Verify official links</Link><Link className="button-secondary" href="/sources">See every source</Link></nav><AdsterraArticleBottom/></main>}
