import type { Metadata } from "next";
import Link from "next/link";
import { editorialSignals, faqs, guideClusters, heroMetrics, officialLinks, siteConfig, toolCards, updateCards, videoGuides, wikiCards } from "@/data/site";
import { AdsterraArticleBottom, AdsterraArticleMid, AdsterraArticleTop } from "@/components/ads";
import { FaqJsonLd, WebSiteJsonLd } from "@/components/seo/JsonLd";
import { SectionHeader, TrustNote } from "@/components/ui/content";
import { BrandHero } from "@/components/home/BrandHero";

export const metadata:Metadata={title:"PokeMMO B2/W2 Release Status & Preview Tracker",description:siteConfig.description,alternates:{canonical:siteConfig.domain},openGraph:{title:"PokeMMO B2/W2 Release Status & Preview Tracker",description:siteConfig.description,url:siteConfig.domain,type:"website",images:[{url:"/opengraph-image"}]}};
function CardGrid({items}:{items:readonly {title:string;href:string;eyebrow:string;description:string}[]}){return <div className="mt-6 grid gap-4 md:grid-cols-3">{items.map((item)=><Link key={`${item.href}-${item.title}`} href={item.href} className="content-card"><span className="mini-label">{item.eyebrow}</span><h3 className="mt-3 text-xl font-bold text-white">{item.title}</h3><p className="mt-2 text-sm leading-6 text-white/65">{item.description}</p></Link>)}</div>}
export default function HomePage(){return <main><WebSiteJsonLd/><FaqJsonLd items={faqs.home}/><BrandHero/>
 <section className="border-y border-white/10 bg-black/25"><div className="mx-auto grid max-w-7xl gap-px px-4 py-5 sm:grid-cols-2 lg:grid-cols-4">{heroMetrics.map((metric)=><div key={metric.label} className="bg-white/[0.03] px-4 py-4"><div className="text-2xl font-bold text-cyan-300">{metric.value}</div><div className="mt-1 text-sm font-semibold text-white">{metric.label}</div><div className="mt-1 text-sm text-white/60">{metric.note}</div></div>)}</div></section><AdsterraArticleTop/>
 <section className="mx-auto max-w-7xl px-4 py-12"><SectionHeader eyebrow="Current answer" title="Announced, with a preview on September 19" copy="PokeMMO has announced B2/W2 and a preview weekend date. The exact start time, end time, access instructions, progress persistence and final release date are still open questions."/><div className="mt-6 grid gap-4 lg:grid-cols-[1.2fr_0.8fr]"><article className="content-card border-cyan-300/25"><h3 className="text-2xl font-bold text-white">What is official today</h3><ul className="mt-5 grid gap-3 text-sm leading-6 text-white/68"><li>• B2/W2 was announced by PokeMMO.</li><li>• Preview Weekend is dated September 19, 2026.</li><li>• The official client remains at pokemmo.com/downloads.</li></ul><Link className="button-primary mt-6 inline-flex" href="/preview">Read the preview guide</Link></article><article className="content-card border-amber-300/20"><h3 className="text-2xl font-bold text-white">What is not confirmed</h3><ul className="mt-5 grid gap-3 text-sm leading-6 text-white/68"><li>• Final release date</li><li>• Exact preview hours</li><li>• Preview-specific file requirements</li><li>• Individual feature parity</li></ul><Link className="button-secondary mt-6 inline-flex" href="/features">Check each feature</Link></article></div></section>
 <AdsterraArticleMid/><section className="bg-white/[0.025]"><div className="mx-auto max-w-7xl px-4 py-12"><SectionHeader eyebrow="Use now" title="Countdown and evidence tools" copy="These tools work from dated static records and never infer that the preview is live."/><CardGrid items={toolCards}/></div></section>
 <section className="mx-auto max-w-7xl px-4 py-12"><SectionHeader eyebrow="Timeline" title="Official milestones and next checks" copy="The updates page keeps announcements separate from the questions we are watching."/><CardGrid items={updateCards}/></section>
 <section className="bg-black/25"><div className="mx-auto grid max-w-7xl gap-10 px-4 py-12 lg:grid-cols-2"><div><SectionHeader eyebrow="Prepare" title="Guides with enough evidence" copy="Only the preparation and safety guides are live before the preview. Story, cap and location pages wait for direct observations."/><div className="mt-6 grid gap-3">{guideClusters.map((item)=><Link key={item.href+item.title} href={item.href} className="row-link"><span><strong>{item.title}</strong><small>{item.description}</small></span><span>→</span></Link>)}</div></div><div><SectionHeader eyebrow="Evidence index" title="Find the owner of each question" copy="Use the index to distinguish release, side-content and held exact-data topics."/><div className="mt-6 grid gap-3">{wikiCards.map((item)=><Link key={item.href+item.title} href={item.href} className="row-link"><span><strong>{item.title}</strong><small>{item.description}</small></span><span>→</span></Link>)}</div></div></div></section>
 <AdsterraArticleBottom/><section className="mx-auto max-w-7xl px-4 py-12"><SectionHeader eyebrow="Source priority" title="Start with official PokeMMO pages" copy="Community and creator references help identify player questions; official pages lead on dates, access and implementation."/><div className="mt-6 grid gap-4 md:grid-cols-3">{officialLinks.map((item)=><a key={item.href} href={item.href} target="_blank" rel="noreferrer" className="content-card"><span className="mini-label">{item.eyebrow}</span><h3 className="mt-3 text-lg font-bold text-white">{item.title}</h3><p className="mt-2 text-sm text-white/65">{item.description}</p></a>)}</div><div className="mt-6 grid gap-4 md:grid-cols-3">{editorialSignals.map((item)=><TrustNote key={item.title} title={item.title} body={item.body}/>)}</div></section>
 <section className="bg-white/[0.025]"><div className="mx-auto max-w-7xl px-4 py-12"><SectionHeader eyebrow="Creator context" title="Useful PokeMMO viewing—not B2/W2 proof" copy="These Patrouski videos show persistent demand for Unova, beginner and economy help. Their format informs our checklists; unreleased claims still need separate evidence."/><div className="mt-6 grid gap-4 md:grid-cols-3">{videoGuides.map((item)=><a key={item.href} href={item.href} target="_blank" rel="noreferrer" className="content-card"><span className="mini-label">{item.source}</span><h3 className="mt-3 text-lg font-bold text-white">{item.title}</h3><p className="mt-2 text-sm text-white/65">{item.description}</p></a>)}</div></div></section>
 <section className="mx-auto max-w-7xl px-4 py-12"><SectionHeader eyebrow="Quick answers" title="PokeMMO B2/W2 FAQ"/><div className="mt-6 grid gap-4 md:grid-cols-2">{faqs.home.map((item)=><article key={item.q} className="content-card"><h3 className="text-lg font-bold text-white">{item.q}</h3><p className="mt-2 text-sm leading-6 text-white/68">{item.a}</p></article>)}</div></section>
 </main>}
