import type { Metadata } from "next";
import Link from "next/link";
import { siteConfig } from "@/data/site";
import { previewMilestone } from "@/data/release-milestones";
import { AdsterraArticleBottom, AdsterraArticleMid, AdsterraArticleTop } from "@/components/ads";
import { BreadcrumbJsonLd, FaqJsonLd } from "@/components/seo/JsonLd";
import { Breadcrumbs, PageIntro, SectionHeader } from "@/components/ui/content";

const faq=[
 {q:"When is the PokeMMO B2/W2 preview?",a:"The official PokeMMO homepage lists September 19, 2026. An exact start time and end time were not listed when checked on September 5."},
 {q:"How do I join the preview?",a:"Preview-specific access instructions are not confirmed yet. Watch the official homepage and forum rather than downloading an unofficial client."},
 {q:"Will preview progress carry over?",a:"We did not find an official persistence answer. Treat the event as testing and do not plan around permanent progress."},
 {q:"Do I need a Black 2 or White 2 ROM?",a:"Current general PokeMMO support pages describe existing requirements, not a confirmed B2/W2 preview requirement. Use only official support and legally owned compatible files."},
 {q:"Is September 19 the final release date?",a:"No. It is the announced preview date; no final B2/W2 release date is confirmed on this site."}
];
export const metadata:Metadata={title:"PokeMMO B2/W2 Preview Weekend Guide (September 2026)",description:"See the official September 19 PokeMMO B2/W2 preview date, safe preparation steps, current unknowns and source-checked access updates.",alternates:{canonical:`${siteConfig.domain}/preview`}};
export default function PreviewPage(){return <main className="mx-auto max-w-7xl px-4 py-10"><BreadcrumbJsonLd items={[{name:"Home",href:"/"},{name:"Preview",href:"/preview"}]}/><FaqJsonLd items={faq}/><Breadcrumbs items={[{label:"Preview",href:"/preview"}]}/><PageIntro eyebrow="Official date · checked September 5" title="PokeMMO B2/W2 preview weekend guide" description="The preview is announced for September 19, 2026. Access method, exact start time, end time and progress persistence are still waiting for official answers."/><AdsterraArticleTop/>
 <section className="mt-8 grid gap-4 lg:grid-cols-3"><article className="content-card"><span className="mini-label">Date</span><h2 className="mt-3 text-3xl font-extrabold text-white">Sep 19, 2026</h2><p className="mt-2 text-sm text-white/60">Official preview date; not a final release date.</p></article><article className="content-card"><span className="mini-label">Access</span><h2 className="mt-3 text-xl font-bold text-white">Instructions pending</h2><p className="mt-2 text-sm text-white/60">Use the official client pages only. No separate preview client is linked here.</p></article><article className="content-card"><span className="mini-label">Progress</span><h2 className="mt-3 text-xl font-bold text-white">Carry-over unknown</h2><p className="mt-2 text-sm text-white/60">Do not assume test progress will persist.</p></article></section>
 <section className="mt-10 grid gap-5 lg:grid-cols-[1.1fr_0.9fr]"><article className="content-card"><SectionHeader eyebrow="What you can do now" title="Prepare without guessing"/><ol className="mt-5 grid gap-4 text-sm leading-6 text-white/68"><li><strong className="text-white">1. Confirm account access.</strong> Sign in through the normal official client before event day; this checklist does not guarantee preview access.</li><li><strong className="text-white">2. Bookmark official pages.</strong> Save the homepage, forum, downloads and support pages so last-minute instructions come from the right place.</li><li><strong className="text-white">3. Protect your current setup.</strong> Follow official guidance for any client or file change. Never download ROM files from this site.</li><li><strong className="text-white">4. Choose test questions.</strong> Check side activities, encounters, caps and progress behavior, but record observations as observations—not universal facts.</li></ol></article><aside className="content-card"><SectionHeader eyebrow="Do not assume" title="Four open questions"/><ul className="mt-5 grid gap-3 text-sm text-white/65"><li>Exact UTC start time</li><li>Preview end time</li><li>Preview-specific file requirements</li><li>Whether progress persists</li></ul><a className="button-primary mt-6 inline-flex" href={previewMilestone.sourceUrl} target="_blank" rel="noreferrer">Read the official announcement</a></aside></section>
 <AdsterraArticleMid/><section className="mt-10 content-card"><SectionHeader eyebrow="Questions" title="Preview FAQ"/><div className="mt-5 grid gap-3">{faq.map((item)=><details key={item.q} className="rounded-xl border border-white/10 p-4"><summary className="cursor-pointer font-bold text-white">{item.q}</summary><p className="mt-3 text-sm text-white/65">{item.a}</p></details>)}</div></section><nav className="mt-8 flex flex-wrap gap-3"><Link className="button-secondary" href="/calculator">Open countdown</Link><Link className="button-secondary" href="/download">Safe setup status</Link><Link className="button-secondary" href="/features">Feature tracker</Link><Link className="button-secondary" href="/trello">Official links</Link></nav><AdsterraArticleBottom/></main>}
